// Generated by scripts/recovery/generate-shims.mjs. A compat shim is correct when every old name IS the owner's export.
import test from "node:test";
import assert from "node:assert/strict";
import * as shim0 from "../dist/index.js";
import * as owner0 from "obix-core-runtime";

test("obix-sdk-core: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim0["LifecycleHook"], owner0["LifecycleHook"], "LifecycleHook");
  assert.equal(shim0["ObixRuntime"], owner0["ObixRuntime"], "ObixRuntime");
  assert.equal(shim0["PolicyEngine"], owner0["PolicyEngine"], "PolicyEngine");
  assert.equal(shim0["StateHaltEngine"], owner0["StateHaltEngine"], "StateHaltEngine");
  assert.deepEqual(Object.keys(shim0).sort(), ["LifecycleHook","ObixRuntime","PolicyEngine","StateHaltEngine"]);
});
