// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { LifecycleHook, ObixRuntime, PolicyEngine, StateHaltEngine } from "obix-core-runtime";
export type { Action, ComponentDefinition, ComponentInstance, ComponentLogic, HaltRecommendation, LifecycleHandler, Policy, PolicyResult, RenderFn, StateHaltConfig } from "obix-core-runtime";
